/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a job_adaptor.h: jobs/com.vicr123.thelibs.tjob.Job.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef JOB_ADAPTOR_H
#define JOB_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.vicr123.thelibs.tjob.Job
 */
class JobAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.vicr123.thelibs.tjob.Job")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.vicr123.thelibs.tjob.Job\">\n"
"    <signal name=\"ProgressChanged\">\n"
"      <arg direction=\"out\" type=\"t\" name=\"progress\"/>\n"
"    </signal>\n"
"    <signal name=\"TotalProgressChanged\">\n"
"      <arg direction=\"out\" type=\"t\" name=\"totalProgress\"/>\n"
"    </signal>\n"
"    <signal name=\"StateChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"state\"/>\n"
"    </signal>\n"
"    <method name=\"Progress\">\n"
"      <arg direction=\"out\" type=\"t\"/>\n"
"    </method>\n"
"    <method name=\"TotalProgress\">\n"
"      <arg direction=\"out\" type=\"t\"/>\n"
"    </method>\n"
"    <method name=\"State\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    JobAdaptor(QObject *parent);
    virtual ~JobAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    qulonglong Progress();
    QString State();
    qulonglong TotalProgress();
Q_SIGNALS: // SIGNALS
    void ProgressChanged(qulonglong progress);
    void StateChanged(const QString &state);
    void TotalProgressChanged(qulonglong totalProgress);
};

#endif
