/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a manager_adaptor.h: jobs/com.vicr123.thelibs.tjob.Manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MANAGER_ADAPTOR_H
#define MANAGER_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.vicr123.thelibs.tjob.Manager
 */
class ManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.vicr123.thelibs.tjob.Manager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.vicr123.thelibs.tjob.Manager\">\n"
"    <signal name=\"JobAdded\">\n"
"      <arg direction=\"out\" type=\"o\" name=\"job\"/>\n"
"    </signal>\n"
"    <method name=\"Jobs\">\n"
"      <arg direction=\"out\" type=\"ao\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ManagerAdaptor(QObject *parent);
    virtual ~ManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QList<QDBusObjectPath> Jobs();
Q_SIGNALS: // SIGNALS
    void JobAdded(const QDBusObjectPath &job);
};

#endif
